### ISSUE TITLE
fail patch   if AirPlay

### ISSUE THREAD

**Issue by xenatt** [toleda/audio_RealtekALC#12]
I found many case fail to detect codec b'cuz Have AirPlay both.

**Comment by toleda** [comment]
Onboard audio codec and AirPlay are not related.  AirPlay does not required working onboard audio. No onboard codec indicates OS X does not detect the codec.  See https://github.com/toleda/audio_ALC_guides/blob/master/No%20Audio%20Devices%20-%20Realtek%20ALC%20AppleHDA%20%5BGuide%5D.pdf

**Comment by xenatt** [comment]
z97-d3h h97-d3h

**Comment by toleda** [comment]
??

**Comment by xenatt** [comment]
two model of motherboard I found issue ,this has android streaming tv(airply support) on network. 
But same mother board not found issue.

**Comment by toleda** [comment]
Again, onboard audio and AirPlay are not related.  AirPlay (w/WiFi) works with or without onboard audio.
