### ISSUE TITLE
space in script path causes errors

### ISSUE THREAD

**Issue by khtang** [toleda/audio_RealtekALC#13]
if any space is presented in the script path, patching fails and ambiguous redirect errors happen as the plist is being generated. Maybe add "no spaces" in path as part of the instructions or update bash to handle spaces? 

thanks for your work!

**Comment by toleda** [comment]
Example?

**Comment by khtang** [comment]
oh I feel like an idiot. I mixed up one of the other fix scripts (AppleHDA8Series) in the same folder and thought that was from your repo. Sorry for the waste of time.
