### ISSUE TITLE
No Audio on El Capitan

### ISSUE THREAD

**Issue by alxgarza** [toleda/audio_RealtekALC#22]
I'm having trouble getting audio out of GA-Z77X-UD5H with ALC898.

Using clover.

This is the output of audio_cloverALC-110_v1.0h.command:

EFI partition is mounted
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

OK to patch
Confirm Realtek ALC898 (y/n): y
Enable HD4600 HDMI audio (y/n): n
Clover Audio ID Injection (y/n): y
Use Audio ID: 1 (y/n): y

Download ALC898 files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24769  100 24769    0     0  21697      0  0:00:01  0:00:01 --:--:-- 21708
Edit config.plist/Devices/Audio/Inject/1
Edit config.plist/SystemParameters/InjectKexts/YES
Download kext patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1404  100  1404    0     0   4929      0 --:--:-- --:--:-- --:--:--  4943
Install /Volumes/EFI/EFI/CLOVER/kexts/10.11/realtekALC.kext
Download config kext and install ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3586  100  3586    0     0  12401      0 --:--:-- --:--:-- --:--:-- 12408
Install System/Library/Extensions/AppleHDA.kext/ALC898 zml files
Fix permissions ...
Kernel cache...
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext FVInjector.kext
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleHDA898.kext
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleHDAHardwareConfigDriver.kext
AppleDataSetManagement.kext - dependency for com.apple.iokit.IOAHCIBlockStorage lacks valid OSBundleCompatibleVersion.
AppleDataSetManagement.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
AppleDataSetManagement.kext - dependency for com.apple.iokit.IOAHCIBlockStorage lacks valid OSBundleCompatibleVersion.
/System/Library/PrelinkedKernels/prelinkedkernel not cached.
Successfully updated disk1s3.
kextcache updated critical boot files, requesting launchd reboot

Install finished, restart required.
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

If I check if if it loaded:
sudo kextload "/System/Library/Extensions/AppleHDA.kext"
I get:
/System/Library/Extensions/AppleHDA.kext failed to load - (libkern/kext) different version/uuid already loaded; check the system/kernel logs for errors or try kextutil(8).

Any ideas what I might be doing wrong?

Thanks

**Comment by toleda** [comment]
Remove AppleHDA898.kext.

**Comment by alxgarza** [comment]
Thanks!

That fix my audio problem.
