### ISSUE TITLE
cloverALC.command does not work for ALC1150 on MSI Z170A Gaming Pro

### ISSUE THREAD

**Issue by saihv** [toleda/audio_RealtekALC#27]
It says Error: IOReg/HDEF; BIOS/audio/disabled or ACPI problem.

My motherboard is us.msi.com/product/mb/Z170A-GAMING-PRO.html. Chip is the Realtek 1150. Do I need a special DSDT for this? Thanks!

**Comment by toleda** [comment]
!00 Series uses dsdt/HDAS for audio, OS X uses HDEF.  Install https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-1-100-hdas.zip and restart.  Run script.

**Comment by saihv** [comment]
Hey, so I installed the SSDT and reran the script and it worked, but I don't see the patched kext in System Library Extensions folder, so there's still no audio. I already have SIP disabled completely. Is there anything else I could be  missing? Thanks!

**Comment by saihv** [comment]
Ah, well, ignore that: I tried your cloverALC script instead of this and it works now. Thanks for all your work!
