### ISSUE TITLE
Just a quick tip...

### ISSUE THREAD

**Issue by philippetev** [toleda/audio_RealtekALC#3]
Just a quick tip, you can use the bash wildcard symbols in the case statements too like this:

line 663:
10.8.5|10.9|10.9.1|10.9.2|10.9.3|10.9.4|10.9.5|10.9.6|10.10|10.10.1|10.10.2|10.10.3|10.10.4 )
may become
10.8.5|10.9*|10.10*)

The star (*) will handle every version from 10.10 to whatever version may be released.

line 708:
10.8|10.8.1|10.8.2|10.8.3|10.8.4 )
may become
10.8|10.8.*[1-4] )

This one will handle all 10.8.x versions, except 10.8.5.

**Comment by toleda** [comment]
v1.0.4.
