### ISSUE TITLE
No audio codec detected

### ISSUE THREAD

**Issue by boyriot** [toleda/audio_RealtekALC#31]
Hi, I tried to install the script to confirm audio injection is ok but no luck :
```
No audio codec detected
Verify BIOS, hardware, etc.

logout
Saving session...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.
```

my motherboard is Biostar TA870+ v2, onboard audio Realtek ALC892

**Comment by toleda** [comment]
OS X does not see the codec, not a script problem.  DPCIManager shows CodecID when codec is working. Verify BIOS/HD Audio/enabled.

**Comment by boyriot** [comment]
how do I enable HD Audio? I don't see any settings in BIOS to enable that.

**Comment by boyriot** [comment]
ok, I just patched using https://github.com/toleda/audio_kext_enabler but it only enable HDMI audio from my graphic card, not Realtek :
```
HDMI audio codec(s)
AMD:      0x1002aa01

Onboard audio codec

Unsupported device, consider Google search
No system files were changed
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by toleda** [comment]
Intel support only.
