### ISSUE TITLE
X99 Update undefined variables

### ISSUE THREAD

**Issue by tnk3r** [toleda/audio_RealtekALC#35]
In the last Case statement.  "audio_alc_x99-hda-100_patch.command"

$gExtensionsDirectory is not defined resulting in 'root' /AppleHDA.kext which would never exist. So permissions would need to be updated elsewhere.

gExtensionsDirectory='/System/Library/Extensions/' 
^^ Should be somewhere before line 100

**Comment by toleda** [comment]
Script updated, thanks.
