### ISSUE TITLE
Sierra Support

### ISSUE THREAD

**Issue by Aghassi** [toleda/audio_RealtekALC#36]
It seems this script doesn't support 10.12. Are there plans to update it to support this in the future? I was looking through the code, and I want to assume that adding a check for Sierra and matching that with were El Cap occurs would fix the issue, but I am not totally sure. Just in case I wanted to post here should there be another solution.

**Comment by mrPsycho** [comment]
for me it works with hacks

**Comment by toleda** [comment]
@Aghassi: Sierra commit 10/25/16
@mrPsycho: hacks?

**Comment by Aghassi** [comment]
Thanks!
