### ISSUE TITLE
Error: no IOReg/HDEF; BIOS/audio/disabled or ACPI problem (x99

### ISSUE THREAD

**Issue by grandosegood** [toleda/audio_RealtekALC#42]
Hello there,

i attempted to run this for my realtek alc1150. however, i get the error "Error: no IOReg/HDEF; BIOS/audio/disabled or ACPI problem"

i am running 10.12.6 on my i7-6800k and Asus X99-A/USB 3.1 .  

What would be the next step.

**Comment by grandosegood** [comment]
update: after reading earlier posts, i installed the following ssdt: https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-1-100-hdas.zip

however, the problem is now i get a 'No audio codec detected" Bios is 3701. Onboard audio is enabled in bios.

**Comment by toleda** [comment]
Not correct, HDAS is 100/200 Series chips sets
X99/ALZA, try https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-1-x99-alza.zip

**Comment by grandosegood** [comment]
thank you, after using this SSDT, the patch does complete successfully and audio devices now show up in sound. However, I can't get any sound output from rear green audio jack. having used cloveralc on an x79 machine before, I know how a successful patching should go. What could cause the patch to complete, devices show up in sound prefpane but no audio comes out?

**Comment by toleda** [comment]
Need a controller patch:
Download https://github.com/toleda/audio_CloverALC/blob/master/config-audio_cloverALC-x99.plist.zip
Add config.plist/KernelAndKextPatches/KextsToPatch/10.10-10.11+x99-ALC-Onboard-Audio

**Comment by grandosegood** [comment]
unfortunately, still no audio, including this kextstopatch and the three that come with your cloveralc script. internal speakers is selectable from sound prefpane, but no audio comes out.

**Comment by toleda** [comment]
See README/Problem Reporting, attach requested files.

**Comment by grandosegood** [comment]
problem submitted - it seems that the SSDT provided by RampageDev for the X99 guide causes conflict. will use VoodooHDA or third party audio device until solution can be found. as always, thank you for your time and awesome knowledge!
